"""empty message

Revision ID: 22c0459b2066
Revises: 23cef89d984
Create Date: 2016-04-06 18:41:24.341416

"""

# revision identifiers, used by Alembic.
revision = '22c0459b2066'
down_revision = '23cef89d984'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('news', sa.Column('updated_by', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'updated_by')
    op.drop_column('news', 'updated_at')
    ### end Alembic commands ###
