"""empty message

Revision ID: 32caca1d6e75
Revises: 27e38a6565d1
Create Date: 2017-01-23 21:12:02.353423

"""

# revision identifiers, used by Alembic.
revision = '32caca1d6e75'
down_revision = '27e38a6565d1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('officers', sa.Column('office', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('officers', 'office')
    ### end Alembic commands ###
