"""empty message

Revision ID: bf7eff9fc3de
Revises: 57892038a626
Create Date: 2016-10-30 13:47:34.231336

"""

# revision identifiers, used by Alembic.
revision = 'bf7eff9fc3de'
down_revision = '57892038a626'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('delorme', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('facebook', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('github', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('google', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('instagram', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('linkedin', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('proemail', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('soundcloud', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('twitter', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('vimeo', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('youtube', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'youtube')
    op.drop_column('profiles', 'vimeo')
    op.drop_column('profiles', 'twitter')
    op.drop_column('profiles', 'soundcloud')
    op.drop_column('profiles', 'proemail')
    op.drop_column('profiles', 'linkedin')
    op.drop_column('profiles', 'instagram')
    op.drop_column('profiles', 'google')
    op.drop_column('profiles', 'github')
    op.drop_column('profiles', 'facebook')
    op.drop_column('profiles', 'delorme')
    ### end Alembic commands ###
